trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployStorageAccounts
    displayName: "Deploy Storage Accounts"
    jobs:
      - job: DeployStorage
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: "MeravAzureServiceConnection"
              subscriptionId: "<YOUR_SUBSCRIPTION_ID>"
              action: "Create Or Update Resource Group"
              resourceGroupName: "MyResourceGroup"
              location: "eastus"
              templateLocation: "Linked artifact"
              csmFile: "azure_storage_template.json"
              overrideParameters: "storageAccountName1=mystorageaccount1 storageAccountName2=mystorageaccount2"

  - stage: DeployVM
    displayName: "Deploy Virtual Machine"
    jobs:
      - job: DeployVMJob
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: "MeravAzureServiceConnection"
              subscriptionId: "<YOUR_SUBSCRIPTION_ID>"
              resourceGroupName: "MyResourceGroup"
              location: "eastus"
              templateLocation: "Linked artifact"
              csmFile: "azure_vm_template.json"
              overrideParameters: "vmName=myVM"

  - stage: CopyBlobs
    displayName: "Copy Blobs Between Storage Accounts"
    jobs:
      - job: CopyBlobsJob
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "MeravAzureServiceConnection"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az storage blob copy start-batch \
                  --source-container mycontainer \
                  --destination-container mycontainer \
                  --destination-account-name mystorageaccount2 \
                  --source-account-name mystorageaccount1 \
                  --account-key $(storageAccountKey)
                  
  - stage: MonitorSetup
    displayName: "Deploy Azure Monitor Setup"
    jobs:
      - job: MonitorSetupJob
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy Azure Monitor Setup'
            inputs:
              deploymentScope: 'Resource Group'
              resourceGroupName: 'MyResourceGroup'
              location: 'eastus'
              templateLocation: 'Linked artifact'
              csmFile: 'path/to/azure_monitor_setup.json'
