trigger:
- main  # Change this to the branch you use

pool:
  name: MeravSelfHostedPool  # Uses your personal PC as the agent

steps:
- script: |
    echo "Azure DevOps Self-Hosted Agent Test"
    echo "Running on:"
    systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
  displayName: "System Info (Windows)"

- script: |
    echo "Checking Disk Space:"
    wmic logicaldisk get size,freespace,caption
  displayName: "Check Disk Space (Windows)"

- task: AzureCLI@2
  inputs:
    azureSubscription: "MeravAzureServiceConnection"
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Authenticated using Service Principal!"
      az account show
  displayName: "Azure CLI Connectivity Test"
